version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  sqs:
    image: localstack/localstack
    ports:
      - "4563-4599:4563-4599"
      - "8055:8080"
    environment:
      SERVICES: sqs
      DATA_DIR: /tmp/localstack/data
      AWS_ACCESS_KEY_ID: DOESNT_MATTER
      AWS_SECRET_ACCESS_KEY: DOESNT_MATTER
      AWS_DEFAULT_REGION: us-west-2
      AWS_DEFAULT_OUTPUT: json
    # volumes:
    #   - "sqs:/tmp/localstack"
    # Attempt to create an sqs queue after the service is up (from experience, 10s is sufficient)
    healthcheck:
      test: aws --endpoint-url=http://example-endpoint:8080 sqs create-queue --queue-name=development-queue || true
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 0

  example-endpoint:
    image: mr0cket/http-bin
    restart: always
    ports:
      - 6546:8080
    environment:
      - PORT=8080
